Skip to content
LuigiGf
/
LuigiGf

Type / to search

Code
Issues
Pull requests
2
Actions
Projects
Security
Insights
Generate Datas
Generate Datas #196
Jobs
Run details
Workflow file for this run
.github/workflows/main.yml at fc1cc35
name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: dev-ley
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Update README.md · LuigiGf/LuigiGf@fc1cc35
